development:
  adapter: postgresql
  encoding: unicode
  database: rifando_development
  pool: 5
  host: localhost
  username: rifando
  password: rifando

test:
  adapter: postgresql
  encoding: unicode
  database: rifando_test
  pool: 5
  host: localhost
  username: rifando
  password: rifando

production:
  adapter: postgresql
  encoding: unicode
  database: rifando
  pool: 5
  host: localhost
  username: rifando
  password: rifando
